# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eb65c7eab01df2f0f8e5ff622cacb5be2c6c42ad230696c2d2b40fbd56be97bfab199ec04f7add8e63f3bcbbe0231083b296d4168d578340435fb17207bbff7

test:
  secret_key_base: a975f954d350e7445af2501c18d52c017330b766cf37261e62c05f667e356ca00dc703efe4c19db30b7fca0fec476d442a8246a2fa3aa6cd0d6eb8aee4ce5d62

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
